#!/usr/bin/env python3
"""Generate constant sine samples for rf_nco; no model code is imported.

Uses 70-decimal-digit Taylor arithmetic in the first quadrant and exact integer
symmetry. The RTL initialization loop subsamples this 4096-entry master table.
Run --check to verify the committed artifact without changing any files.
"""

import argparse
from decimal import Decimal, ROUND_HALF_UP, localcontext
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "rtl/nco/sine_lut_12b.svh"
PI = Decimal("3.14159265358979323846264338327950288419716939937510582097494459230781640628620899")
ADDRESS_BITS = 12
CONSTANT_BITS = 48
FRACTION_BITS = 46


def sine(angle: Decimal) -> Decimal:
    term = angle
    total = angle
    k = 1
    while abs(term) > Decimal("1e-65"):
        term *= -angle * angle / Decimal((2 * k) * (2 * k + 1))
        total += term
        k += 1
    return total


def render() -> str:
    quarter = (1 << ADDRESS_BITS) // 4
    with localcontext() as context:
        context.prec = 70
        first_quadrant = [
            sine(PI * Decimal(k) / Decimal(2 * quarter))
            for k in range(quarter + 1)
        ]
        first_quadrant[0], first_quadrant[-1] = Decimal(0), Decimal(1)
        samples = []
        for address in range(1 << ADDRESS_BITS):
            quadrant, offset = divmod(address, quarter)
            magnitude = first_quadrant[offset if quadrant % 2 == 0 else quarter - offset]
            sample = magnitude if quadrant < 2 else -magnitude
            encoded = int((sample * (1 << FRACTION_BITS)).to_integral_value(rounding=ROUND_HALF_UP))
            # Prove the intermediate fixed-point constants do not introduce a
            # double-rounding discrepancy for any supported output width/grid point.
            for bits in range(2, 17):
                peak = (1 << (bits - 1)) - 1
                direct = int((sample * peak).to_integral_value(rounding=ROUND_HALF_UP))
                rounded = (abs(encoded) * peak + (1 << (FRACTION_BITS - 1))) >> FRACTION_BITS
                quantized = -rounded if encoded < 0 else rounded
                if quantized != direct:
                    raise ValueError(f"Double rounding at address={address}, output_bits={bits}")
            samples.append(encoded)
    lines = [
        "// Generated by scripts/generate_nco_lut.py; do not edit.",
        "// round_away(2**46 * sin(2*pi*address/4096)), signed Q2.46 constants.",
        "// Used only for constant ROM initialization, not runtime arithmetic.",
        "function automatic logic signed [47:0] sine_lut_constant(input logic [11:0] address);",
        "    case (address)",
    ]
    for address, sample in enumerate(samples):
        encoded = sample & ((1 << CONSTANT_BITS) - 1)
        lines.append(f"        12'd{address}: sine_lut_constant = 48'sh{encoded:012x};")
    lines += [
        "        default: sine_lut_constant = 48'sh000000000000;",
        "    endcase",
        "endfunction",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != content:
            raise SystemExit(f"LUT is missing or stale: {OUTPUT}")
        print("Committed NCO LUT matches high-precision generator.")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(content)
        print(f"Generated {OUTPUT}")


if __name__ == "__main__":
    main()
