"""Deterministic 70-digit Candidate C production quarter-ROM generator.

M[k] = round-nearest/ties-away(131071*sin(pi*k/32768)), 0 <= k < 16384.
The exact pi/2 endpoint is reconstructed as 131071 outside the ROM.
No verification model or captured data is imported.
"""
import argparse
from decimal import Decimal, ROUND_HALF_UP, localcontext
from pathlib import Path
import sys
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from scripts.generate_nco_lut import sine, PI
OUTPUT = ROOT / 'rtl/nco/high_purity_quarter.svh'


def render():
    with localcontext() as ctx:
        ctx.prec = 70
        lines = ['// Generated by scripts/generate_high_purity_lut.py; do not edit.',
                 '// round-away(131071*sin(pi*k/32768)); k=0..16383; peak bypass.']
        for k in range(16384):
            value = int((Decimal(131071)*sine(PI*Decimal(k)/Decimal(32768))).to_integral_value(rounding=ROUND_HALF_UP))
            lines.append(f"rom[{k}] = 17'd{value};")
        return '\n'.join(lines)+'\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = render()
    if args.check:
        if OUTPUT.read_text() != expected:
            raise SystemExit('Production high-purity ROM differs from deterministic generation')
        print('Production high-purity ROM reproducible: PASS')
    else:
        OUTPUT.write_text(expected)
        print(OUTPUT)
