"""Generate dependency-free ABI constants; --check rejects stale outputs."""
import argparse
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]

def render():
    spec = json.loads((ROOT/'spec/control_registers.json').read_text())
    regs = spec['registers']
    offsets = [r['offset'] for r in regs]
    if len(set(offsets)) != len(offsets) or any(a % 4 or not 0 <= a < 65536 for a in offsets):
        raise ValueError('duplicate, misaligned or out-of-range address')
    constants = [('IP_ID_VALUE',spec['ip_id'],32),('ABI_VERSION_VALUE',spec['abi_version'],32)]
    constants += [('ADDR_'+r['name'],r['offset'],16) for r in regs]
    for group,prefix in [('commands','CMD'),('errors','ERR'),('status','STATUS'),('capabilities','CAP')]:
        constants += [(prefix+'_'+name,1<<bit,32) for name,bit in spec[group].items()]
    constants += [('MODE_'+name,value,32) for name,value in spec['modes'].items()]
    sv = ['// Generated by scripts/generate_control_registers.py; do not edit.', 'package openrf_control_pkg;']
    sv += [f"    localparam logic [{width-1}:0] {name} = {width}'h{value:0{width//4}x};" for name,value,width in constants]
    sv += ['endpackage','']
    py = ['"""Generated CSR ABI constants; do not edit."""']
    py += [f'{name} = 0x{value:0{width//4}x}' for name,value,width in constants]
    py += ['REGISTERS = '+repr({r['offset']:r['name'] for r in regs}), 'ACCESS = '+repr({r['offset']:r['access'] for r in regs}), '']
    return {'rtl/control/openrf_control_pkg.sv':'\n'.join(sv),'models/python/control_registers.py':'\n'.join(py)}

def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    for name,text in render().items():
        path=ROOT/name
        if args.check:
            if not path.exists() or path.read_text()!=text:raise SystemExit(f'Stale generated file: {name}')
        else:path.write_text(text)
    print('Control register map: PASS')

if __name__=='__main__':main()
